#!/usr/bin/env bash
#
# ░█▀▄░█▀█░█▀▀░█▄█░█▀█░█▀▀░▄▀▄
# ░█░█░█░█░▀▀█░█░█░█▀█░▀▀█░█\█
# ░▀▀░░▀░▀░▀▀▀░▀░▀░▀░▀░▀▀▀░░▀\
#

die() {
    echo "$1"
    exit "$2"
}

# check args
command=$1
[[ -z $command ]] && command=hits

# available commands supplied as an arg to this script are:
# insertions, evictions, hits, misses, ratio

# check dig is installed
[[ -x $(command -v dig) ]] || die "No dig" 1

# check dnsmasq is running
[[ $(pgrep dnsmasq > /dev/null) -eq 0 ]] || die "No dnsmasq" 2

if [ $command == "ratio" ]; then
    hits=$(dig +short chaos txt hits.bind | tr -d \")
    misses=$(dig +short chaos txt misses.bind | tr -d \")
    ratio=$(echo "$hits * 100 / ($hits + $misses)" | bc)
    echo "${ratio}%"
else
    dig +short chaos txt ${command}.bind | tr -d \"
fi
